In [1]:
import torch

# Autograd Function to Compute Gradient Automatically
### Gradient is essential to optimize models
### The following example shows the gradient of some function w.r.t. x

In [15]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y * 2
print(z)
z = z.mean()
print(z)
# z has a single mean scaler value that's why no need to pass a vector in Backward function
z.backward() # dz/dx
x.grad

tensor([ 0.7692, -1.1365,  1.8479], requires_grad=True)
tensor([2.7692, 0.8635, 3.8479], grad_fn=<AddBackward0>)
tensor([15.3373,  1.4911, 29.6128], grad_fn=<MulBackward0>)
tensor(15.4804, grad_fn=<MeanBackward0>)


tensor([3.6923, 1.1513, 5.1305])

In [18]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y * 2
print(z)
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
print(v)
# z has multiple (not a scaler) values that's why need to pass a vector in Backward function
z.backward(v) # dz/dx
x.grad
x = x.requires_grad_(False)
print(x)

tensor([ 0.5056, -0.3569, -1.5549], requires_grad=True)
tensor([2.5056, 1.6431, 0.4451], grad_fn=<AddBackward0>)
tensor([12.5559,  5.3996,  0.3963], grad_fn=<MulBackward0>)
tensor([0.1000, 1.0000, 0.0010])
tensor([ 0.5056, -0.3569, -1.5549])
